/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Entity.Constants;
import Entity.Fonts;
import java.awt.Color;

/**
 *
 * @author osmel
 */
public class UILogin extends javax.swing.JFrame {
    
    private int xMouse, yMouse;
    
    private Fonts font;
    
    public UILogin() {
        initComponents();
        init();
    }
    
    private void init() {
        setLocationRelativeTo(null);
        setTitle(Constants.TITLE + " - Iniciar sesión");
        font();
    }
    
    private void font() {
        font = new Fonts();
        
        jLabelTitle.setFont(font.Font(font.ROBOTO_MEDIUM, 1, 24));
        jLabelUser.setFont(font.Font(font.ROBOTO_BOLD, 0, 11));
        jLabelPassword.setFont(font.Font(font.ROBOTO_BOLD, 0, 11));
        jTextFieldUser.setFont(font.Font(font.ROBOTO_REGULAR, 0, 14));
        jPasswordFieldPassword.setFont(font.Font(font.ROBOTO_REGULAR, 0, 14));
        jButtonLogin.setFont(font.Font(font.ROBOTO_BOLD, 1, 11));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelRegister = new javax.swing.JLabel();
        jLabelForgotPassword = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabelPaneRegister = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelOffline = new javax.swing.JLabel();
        jLogo = new javax.swing.JLabel();
        jLabelLogoBg = new javax.swing.JLabel();
        jLabelBgPane = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonMinimize = new javax.swing.JButton();
        jPanelHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegister.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(224, 224, 224));
        jLabelRegister.setText("Regístrese aquí.");
        jLabelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister.setPreferredSize(new java.awt.Dimension(78, 30));
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        jLabelForgotPassword.setBackground(new java.awt.Color(204, 204, 204));
        jLabelForgotPassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelForgotPassword.setForeground(new java.awt.Color(224, 224, 224));
        jLabelForgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelForgotPassword.setText("¿Olvidó su contraseña?");
        jLabelForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 160, -1));

        jLabelPassword.setBackground(new java.awt.Color(204, 204, 204));
        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(224, 224, 224));
        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPassword.setText("Contraseña");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 334, -1));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(224, 224, 224));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("INICIAR SESIÓN");
        jLabelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 334, -1));

        jLabelUser.setBackground(new java.awt.Color(204, 204, 204));
        jLabelUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(224, 224, 224));
        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUser.setText("Usuario");
        jPanel1.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 334, -1));

        jLabelMessage.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelMessage.setForeground(new java.awt.Color(76, 175, 80));
        jLabelMessage.setText("¿No tiene cuenta?");
        jLabelMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMessage.setPreferredSize(new java.awt.Dimension(89, 30));
        jPanel1.add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 90, -1));

        jButtonLogin.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(240, 240, 240));
        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Boton_100x50.png"))); // NOI18N
        jButtonLogin.setText("Iniciar sesión");
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.setContentAreaFilled(false);
        jButtonLogin.setFocusPainted(false);
        jButtonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLogin.setPreferredSize(new java.awt.Dimension(100, 50));
        jButtonLogin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Boton_100x50.png"))); // NOI18N
        jButtonLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Boton_hover_100x50.png"))); // NOI18N
        jButtonLogin.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Boton_100x50.png"))); // NOI18N
        jButtonLogin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Boton_hover_100x50.png"))); // NOI18N
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 110, -1));

        jLabelPaneRegister.setForeground(new java.awt.Color(153, 255, 255));
        jLabelPaneRegister.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPaneRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Buton2_220x30.png"))); // NOI18N
        jLabelPaneRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelPaneRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jTextFieldUser.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldUser.setForeground(new java.awt.Color(224, 224, 224));
        jTextFieldUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(76, 175, 80)));
        jPanel1.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 260, 40));

        jPasswordFieldPassword.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordFieldPassword.setForeground(new java.awt.Color(224, 224, 224));
        jPasswordFieldPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(76, 175, 80)));
        jPanel1.add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 260, 40));

        jLabelOffline.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelOffline.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOffline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOffline.setText("Continuar modo desconectado");
        jLabelOffline.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelOffline.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelOffline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOfflineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelOfflineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelOfflineMouseExited(evt);
            }
        });
        jPanel1.add(jLabelOffline, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 334, 20));

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Logos/SueloSmart_250x250.png"))); // NOI18N
        jLogo.setPreferredSize(new java.awt.Dimension(240, 240));
        jPanel1.add(jLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabelLogoBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logos/bg_300x300.png"))); // NOI18N
        jPanel1.add(jLabelLogoBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabelBgPane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logos/pane_bg_320x430.png"))); // NOI18N
        jPanel1.add(jLabelBgPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 430));

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/close.png"))); // NOI18N
        jButtonExit.setBorderPainted(false);
        jButtonExit.setContentAreaFilled(false);
        jButtonExit.setFocusPainted(false);
        jButtonExit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/close.png"))); // NOI18N
        jButtonExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/close_hover.png"))); // NOI18N
        jButtonExit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/close.png"))); // NOI18N
        jButtonExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/close_hover.png"))); // NOI18N
        jButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonExitMousePressed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 18, 16, 16));

        jButtonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/minimize.png"))); // NOI18N
        jButtonMinimize.setBorderPainted(false);
        jButtonMinimize.setContentAreaFilled(false);
        jButtonMinimize.setFocusPainted(false);
        jButtonMinimize.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/minimize.png"))); // NOI18N
        jButtonMinimize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/minimize_hover.png"))); // NOI18N
        jButtonMinimize.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/minimize.png"))); // NOI18N
        jButtonMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/minimize_hover.png"))); // NOI18N
        jButtonMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMinimizeMousePressed(evt);
            }
        });
        jPanel1.add(jButtonMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 18, 16, 16));

        jPanelHeader.setBackground(new java.awt.Color(51, 51, 51));
        jPanelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelHeaderMouseDragged(evt);
            }
        });
        jPanelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 334, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelOfflineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOfflineMouseClicked
        this.dispose();
        new UILlPl().setVisible(true);
    }//GEN-LAST:event_jLabelOfflineMouseClicked

    private void jButtonExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMousePressed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitMousePressed

    private void jButtonMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizeMousePressed
        setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizeMousePressed

    private void jPanelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelHeaderMousePressed

    private void jPanelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - xMouse, this.getLocation().y + evt.getY() - yMouse);
    }//GEN-LAST:event_jPanelHeaderMouseDragged

    private void jLabelOfflineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOfflineMouseEntered
        jLabelOffline.setForeground(Color.decode("#E0E0E0"));
    }//GEN-LAST:event_jLabelOfflineMouseEntered

    private void jLabelOfflineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOfflineMouseExited
        jLabelOffline.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_jLabelOfflineMouseExited

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
        this.dispose();
        new UIRegister().setVisible(true);
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UILogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonMinimize;
    private javax.swing.JLabel jLabelBgPane;
    private javax.swing.JLabel jLabelForgotPassword;
    private javax.swing.JLabel jLabelLogoBg;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelOffline;
    private javax.swing.JLabel jLabelPaneRegister;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
