/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Entity.Constants;
import Entity.Fonts;

/**
 *
 * @author osmel
 */
public class UIRegister extends javax.swing.JFrame {

    private int xMouse, yMouse;

    private Fonts font;

    public UIRegister() {
        initComponents();
        init();
    }

    private void init() {
        setLocationRelativeTo(null);
        setTitle(Constants.TITLE + " - Crear cuenta");
        font();
    }

    private void font() {
        font = new Fonts();

        jLabelTitle.setFont(font.Font(font.ROBOTO_MEDIUM, 1, 24));
        jLabelUser.setFont(font.Font(font.ROBOTO_BOLD, 0, 11));
        jLabelPassword.setFont(font.Font(font.ROBOTO_BOLD, 0, 11));
        jLabelRepeatPassword.setFont(font.Font(font.ROBOTO_BOLD, 0, 11));
        jTextFieldUser.setFont(font.Font(font.ROBOTO_REGULAR, 0, 14));
        jPasswordFieldPassword.setFont(font.Font(font.ROBOTO_REGULAR, 0, 14));
        jPasswordFieldRepeatPassword.setFont(font.Font(font.ROBOTO_REGULAR, 0, 14));
        jButtonRegister.setFont(font.Font(font.ROBOTO_BOLD, 1, 11));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelRepeatPassword = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jLabelPaneRegister = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordFieldRepeatPassword = new javax.swing.JPasswordField();
        jLogo = new javax.swing.JLabel();
        jLabelLogoBg = new javax.swing.JLabel();
        jLabelBgPane = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonMinimize = new javax.swing.JButton();
        jPanelHeader = new javax.swing.JPanel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(224, 224, 224));
        jLabelLogin.setText("Inicie sesión aquí");
        jLabelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogin.setPreferredSize(new java.awt.Dimension(78, 30));
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        jLabelRepeatPassword.setBackground(new java.awt.Color(204, 204, 204));
        jLabelRepeatPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRepeatPassword.setForeground(new java.awt.Color(224, 224, 224));
        jLabelRepeatPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRepeatPassword.setText("Repetir contraseña");
        jPanel1.add(jLabelRepeatPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 334, -1));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(224, 224, 224));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("CREAR CUENTA");
        jLabelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 334, -1));

        jLabelUser.setBackground(new java.awt.Color(204, 204, 204));
        jLabelUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(224, 224, 224));
        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUser.setText("Usuario");
        jPanel1.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 334, -1));

        jLabelMessage.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelMessage.setForeground(new java.awt.Color(76, 175, 80));
        jLabelMessage.setText("¿Ya tiene una cuenta?");
        jLabelMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMessage.setPreferredSize(new java.awt.Dimension(89, 30));
        jPanel1.add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 100, -1));

        jButtonRegister.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(240, 240, 240));
        jButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Boton_100x50.png"))); // NOI18N
        jButtonRegister.setText("Registrar");
        jButtonRegister.setBorderPainted(false);
        jButtonRegister.setContentAreaFilled(false);
        jButtonRegister.setFocusPainted(false);
        jButtonRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegister.setPreferredSize(new java.awt.Dimension(100, 50));
        jButtonRegister.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Boton_100x50.png"))); // NOI18N
        jButtonRegister.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Boton_hover_100x50.png"))); // NOI18N
        jButtonRegister.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Boton_100x50.png"))); // NOI18N
        jButtonRegister.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Boton_hover_100x50.png"))); // NOI18N
        jPanel1.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 110, -1));

        jLabelPaneRegister.setForeground(new java.awt.Color(153, 255, 255));
        jLabelPaneRegister.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPaneRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/Buton2_220x30.png"))); // NOI18N
        jLabelPaneRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelPaneRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jTextFieldUser.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldUser.setForeground(new java.awt.Color(224, 224, 224));
        jTextFieldUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(76, 175, 80)));
        jPanel1.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 260, 30));

        jPasswordFieldRepeatPassword.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordFieldRepeatPassword.setForeground(new java.awt.Color(224, 224, 224));
        jPasswordFieldRepeatPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(76, 175, 80)));
        jPanel1.add(jPasswordFieldRepeatPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 260, 30));

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Logos/SueloSmart_250x250.png"))); // NOI18N
        jLogo.setPreferredSize(new java.awt.Dimension(240, 240));
        jPanel1.add(jLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabelLogoBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logos/bg_300x300.png"))); // NOI18N
        jPanel1.add(jLabelLogoBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabelBgPane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logos/pane_bg_320x430.png"))); // NOI18N
        jPanel1.add(jLabelBgPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 430));

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/close.png"))); // NOI18N
        jButtonExit.setBorderPainted(false);
        jButtonExit.setContentAreaFilled(false);
        jButtonExit.setFocusPainted(false);
        jButtonExit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/close.png"))); // NOI18N
        jButtonExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/close_hover.png"))); // NOI18N
        jButtonExit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/close.png"))); // NOI18N
        jButtonExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/close_hover.png"))); // NOI18N
        jButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonExitMousePressed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 18, 16, 16));

        jButtonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/minimize.png"))); // NOI18N
        jButtonMinimize.setBorderPainted(false);
        jButtonMinimize.setContentAreaFilled(false);
        jButtonMinimize.setFocusPainted(false);
        jButtonMinimize.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/minimize.png"))); // NOI18N
        jButtonMinimize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/minimize_hover.png"))); // NOI18N
        jButtonMinimize.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/minimize.png"))); // NOI18N
        jButtonMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buttons/minimize_hover.png"))); // NOI18N
        jButtonMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMinimizeMousePressed(evt);
            }
        });
        jPanel1.add(jButtonMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 18, 16, 16));

        jPanelHeader.setBackground(new java.awt.Color(51, 51, 51));
        jPanelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelHeaderMouseDragged(evt);
            }
        });
        jPanelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 334, 50));

        jPasswordFieldPassword.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordFieldPassword.setForeground(new java.awt.Color(224, 224, 224));
        jPasswordFieldPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(76, 175, 80)));
        jPanel1.add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 260, 30));

        jLabelPassword.setBackground(new java.awt.Color(204, 204, 204));
        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(224, 224, 224));
        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPassword.setText("Contraseña");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 334, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMousePressed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitMousePressed

    private void jButtonMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizeMousePressed
        setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizeMousePressed

    private void jPanelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - xMouse, this.getLocation().y + evt.getY() - yMouse);
    }//GEN-LAST:event_jPanelHeaderMouseDragged

    private void jPanelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelHeaderMousePressed

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        this.dispose();
        new UILogin().setVisible(true);
    }//GEN-LAST:event_jLabelLoginMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonMinimize;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabelBgPane;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLogoBg;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelPaneRegister;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRepeatPassword;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JPasswordField jPasswordFieldRepeatPassword;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
